# Test for GDB pretty printers for Boost.Optional.
#
# This file is part of boost-gdb-printers.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load_lib pretty-printers.exp

pp_gdb_init $BINFILE $srcdir/$subdir

if {![pp_load_printers [list boost.$PP_VERSION.optional]]} {
    perror "could not load pretty printers"
    return
}

if {![pp_run_test boost_optional]} {
    perror "the executable is not a proper pretty printer test"
    return
}

pp_test "empty_opt" {empty boost::optional}
pp_test "opt_int" {boost::optional 42}
pp_test "opt_string" {boost::optional "hello world"}
pp_test "opt_vector" {boost::optional std::vector of length 4, capacity [0-9]+ = \{1, 2, 3, 4\}}

# vim: set shiftwidth=4 softtabstop=4 expandtab:
